version: "3"
services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      VERSION: "1.20"
      TYPE: "SPIGOT"
      EULA: "TRUE"
      MEMORY: 2G
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./data:/data
    networks:
      nginx-proxy:
networks:
  nginx-proxy:
    external: true